import AssetsTable from "../../pageObjects/assetsTable";
describe('Assets Table', () => {
    
  
    Cypress.on('uncaught:exception', (err, runnable) => {
        return false;
    });
    it('should visit the Assets Table page', () => {
        cy.fixture('loginDetails').then(function(data){
        const assetsTables = new AssetsTable()
        assetsTables.openUrl()
        //assetsTables.clickaddAsset()
        //assetsTables.clickactiveCheckbox()
        //assetsTables.enterlocation()
        //cy.wait(5000)
        //assetsTables.selectcompany()
        //assetsTables.selectassetGroup()
        assetsTables.enterID()
        assetsTables.selectopenAsset()
        assetsTables.clickArrow()
        assetsTables.enternotes()
        assetsTables.enterpurchaseValue()
        assetsTables.clicksaveDetails()
        cy.wait(1000)
        assetsTables.selectassetFiles()
        cy.wait(10000)
        assetsTables.selectfileUpload()
        assetsTables.clickfileSave()
        assetsTables.clickimages()
        assetsTables.clickimageUpload()
        cy.wait(5000)
        assetsTables.clickinspection()
        assetsTables.selectinspectionSchedule()
        assetsTables.enterinspectionNotification()
        assetsTables.enterinspectionDuration()
        assetsTables.clicksaveInspection()
        assetsTables.clickoperatingTime()
        assetsTables.clicksaveoperatingTime()
        assetsTables.clickbookableDetails()
        assetsTables.enternoticePeriod()
        assetsTables.clickautoAccept()
        assetsTables.clicksavebookableDetails()
        assetsTables.clickcustomField()
        assetsTables.enterfield1()
        assetsTables.clicksaveCustomfield()
        assetsTables.clickteams()
        assetsTables.clickavailableTeams()
        cy.wait(5000)
        assetsTables.clicksiteDocuments()
        assetsTables.clcikqrcode()
        assetsTables.clickqrGenerate()

    })
})
})